
package br.com.fiap.client.warning;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "WineWarningServiceImplementationService", targetNamespace = "http://winery.fiap.com.br/", wsdlLocation = "http://localhost:8086/WineWarningService?wsdl")
public class WineWarningServiceImplementationService
    extends Service
{

    private static final URL WINEWARNINGSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    private static final WebServiceException WINEWARNINGSERVICEIMPLEMENTATIONSERVICE_EXCEPTION;
    private static final QName WINEWARNINGSERVICEIMPLEMENTATIONSERVICE_QNAME = new QName("http://winery.fiap.com.br/", "WineWarningServiceImplementationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8086/WineWarningService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WINEWARNINGSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION = url;
        WINEWARNINGSERVICEIMPLEMENTATIONSERVICE_EXCEPTION = e;
    }

    public WineWarningServiceImplementationService() {
        super(__getWsdlLocation(), WINEWARNINGSERVICEIMPLEMENTATIONSERVICE_QNAME);
    }

    public WineWarningServiceImplementationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WINEWARNINGSERVICEIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public WineWarningServiceImplementationService(URL wsdlLocation) {
        super(wsdlLocation, WINEWARNINGSERVICEIMPLEMENTATIONSERVICE_QNAME);
    }

    public WineWarningServiceImplementationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WINEWARNINGSERVICEIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public WineWarningServiceImplementationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WineWarningServiceImplementationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WineWarningService
     */
    @WebEndpoint(name = "WineWarningServiceImplementationPort")
    public WineWarningService getWineWarningServiceImplementationPort() {
        return super.getPort(new QName("http://winery.fiap.com.br/", "WineWarningServiceImplementationPort"), WineWarningService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WineWarningService
     */
    @WebEndpoint(name = "WineWarningServiceImplementationPort")
    public WineWarningService getWineWarningServiceImplementationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://winery.fiap.com.br/", "WineWarningServiceImplementationPort"), WineWarningService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WINEWARNINGSERVICEIMPLEMENTATIONSERVICE_EXCEPTION!= null) {
            throw WINEWARNINGSERVICEIMPLEMENTATIONSERVICE_EXCEPTION;
        }
        return WINEWARNINGSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    }

}
