
package br.com.fiap.client.warning;

import jakarta.jws.WebMethod;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "WineWarningService", targetNamespace = "http://winery.fiap.com.br/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface WineWarningService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://winery.fiap.com.br/WineWarningService/sendWarningRequest", output = "http://winery.fiap.com.br/WineWarningService/sendWarningResponse")
    public String sendWarning();

}
